
services:
  mysql:
    image: mysql:latest
    container_name: mysql_financial_dashboard
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: FinancialDashboard
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - financial_dashboard_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  financial_dashboard_network:
    external: true

volumes:
  mysql_data:
    external: true
